### PR TITLE
configure 0 and 3 decimal countries

### PR DESCRIPTION
**Pull request by davvidbaker**
#19 
I went in and changed the currency patterns for currencies with 3 and 0 decimals. I also added tests for these jawns.

There were a few currencies that I did not update:
- CVE because its [decimal status is confusing](https://en.wikipedia.org/wiki/Cape_Verdean_escudo)
- KMF because it uses default arabic locale
- XAF because it uses default french locale

Let me know what you think of this! Thanks!

### CODE REVIEW

**Comment by zephimir** [comment]
Hello, any info on this? I see this was closed but not merged, has it been integrated elsewhere?

**Comment by zephimir** [comment]
> Hello, any info on this? I see this was closed but not merged, has it been integrated elsewhere?

@osrec would you have any info pretty please?

**Comment by osrec** [comment]
Hi @zephimir - while this was a fair amount of time ago, my understanding is that the functionality provided in this pull request is now available in the library, even though it was not directly merged from this pull request (which is why we closed the issue).

**Comment by osrec** [comment]
Actually, after reviewing in a little more detail, we decided not to merge this, as the code was including an override for certain currencies, which breaks the ISO locale based currency formatting logic the library offers. Apologies for the confusion.

**Pull request closed without merging**
